### ISSUE TITLE
What to do about pip 19.1

### ISSUE THREAD

**Issue by jsignell** [pyviz/pyctdev#12]
I have been thinking a lot about this since pip broke editable installs yesterday. (https://discuss.python.org/t/pip-19-1-and-installing-in-editable-mode-with-pyproject-toml/1553/5). I thought #11 would solve our problems, but it created new ones, so I wanted to capture what I have thought about so far. 

I think there are several options. 

1. Pin to <19.1
   - fine solution if this is temporary

2. Use the flag every time you pip install with editable: `pip install -e . --no-use-pep517`
   - PRO: smallest change
   - PRO: stay on latest pip
   - CON: flag is too long to remember
   - CON: flag is controversial and might go away

3. Switch to using `python setup.py develop`
   - PRO: get rid of pyproject.toml
   - PRO: does special things that pip doesn't do (build panel models)
   - CON: no good way to specify build-time dependencies
   - CON: conda doesn't recognize as best version when package already in env

**Comment by jbednar** [comment]
Sounds utterly miserable. All options are quite bad.

**Comment by jsignell** [comment]
Seems likely that the pip people will revert while they discuss https://github.com/pypa/pip/pull/6449. Given that, I propose that we pin under 19.1 for now and wait to see how things shake out.

**Comment by philippjfr** [comment]
Sounds like a plan. What a mess that has been.
